name: signage-capture

# ここを repository_dispatch に置き換え
on:
  repository_dispatch:
    types: [capture]

permissions:
  contents: write
  pages: write

jobs:
  capture:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.57.0-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./signage-screenshot

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: ./signage-screenshot

      - name: Capture screenshot
        run: node scripts/screenshot.js
        working-directory: ./signage-screenshot

      - name: Commit image
        run: |
          git config --global --add safe.directory /__w/signage-screenshot/signage-screenshot
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add latest.png
          git commit -m "update screenshot" || echo "no change"
          git push
        working-directory: ./signage-screenshot
