name: signage-capture

on:
  schedule:
    - cron: "*/15 8-17 * * 1-5"
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.57.0-jammy

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Capture screenshot
        run: node scripts/screenshot.js

      - name: Commit image
        run: |
          git config --global --add safe.directory /__w/signage-screenshot/signage-screenshot
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add latest.png
          git commit -m "update screenshot" || echo "no change"
          git push
