name: signage-capture

on:
  schedule:
    - cron: '30-59/1 23 * * 1-5'  # 23:30–23:59 UTC（= JST 8:20–8:59）
    - cron: '0-30/1 0-8 * * 1-5' # 00:00–08:30 UTC（= JST 9:00–17:40）

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  
jobs:
  capture:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.57.0-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Capture screenshot
        run: node scripts/screenshot.js

      - name: Commit image
        run: |
          git config --global --add safe.directory /__w/signage-screenshot/signage-screenshot
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add latest.png
          git commit -m "update screenshot" || echo "no change"
          git push
